version: '3.8'

services:
  firefox:
    image: selenium/standalone-firefox:110.0
    container_name: firefox
    ports:
      - '4443:4443'
    restart: always

  app:
    build: .
    container_name: 'sberparser'
    ports:
      - 8087:8087
    volumes:
      - .:/home/app
    restart: always
    tty: true
    depends_on:
      - firefox
