version: '3.8'

services:
  # chrome:
  #   image: selenium/standalone-chrome:112.0
  #   container_name: chrome
  #   ports:
  #     - '4444:4444'
  #   restart: always

  firefox:
    image: selenium/standalone-firefox:110.0
    container_name: firefox
    ports:
      - '4444:4444'
    restart: always

  app:
    build: .
    container_name: 'sberparser'
    ports:
      - 8087:8087
    volumes:
      - .:/home/app
    restart: always
    tty: true
    depends_on:
      # - chrome
      - firefox
